version: '3'
services:
  epcc-db:
    container_name: epcc-db
    image: mysql:5.7
    volumes:
      - epcc-db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ;dslagku*(PDSGDS
      MYSQL_DATABASE: EclipsePhaseData
      MYSQL_USER: epcc_www
      MYSQL_PASSWORD: 0928sdGdsfa8#_+
    expose:
      - 3306
    ports:
      - 3306:3306
  epcc:
      container_name: epcc
      image: epcc
      build:
        context: docker/epcc/
      depends_on:
        - epcc-db
      links:
        - epcc-db
      volumes:
        - ./:/var/www/html/
      environment:
        SHELL: /bin/bash
        EPCC_CONFIG_PATH: /etc/epcc/config.ini
        LOCALTIME: UTC
      expose:
        - "80"
      ports:
        - "8080:80"
volumes:
  epcc-db-data:
    driver: local
